import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { apiFetch } from '../lib/api';
import { Bell, Search, AlertTriangle, ShieldAlert, Info, Clock } from 'lucide-react';
import { Badge } from '../components/Badge';

interface AlertEvent {
  id: string;
  incident_id: string | null;
  rule_name: string;
  severity: 'CRITICAL' | 'WARNING' | 'INFO';
  title: string;
  message: string;
  notified: boolean;
  created_at: string;
}

export const Alerts = () => {
  const [searchTerm, setSearchTerm] = useState('');
  
  const { data: alerts, isLoading, error } = useQuery({
    queryKey: ['alerts-history'],
    queryFn: () => apiFetch<AlertEvent[]>('/incidents/alerts/history'),
    refetchInterval: 10000,
  });

  const getSeverityIcon = (severity: string) => {
    switch(severity) {
      case 'CRITICAL': return <ShieldAlert size={16} className="text-[var(--error)]" />;
      case 'WARNING': return <AlertTriangle size={16} className="text-[var(--warning)]" />;
      case 'INFO': return <Info size={16} className="text-[var(--primary-light)]" />;
      default: return <Bell size={16} className="text-[var(--text-secondary)]" />;
    }
  };
  
  const getSeverityBadge = (severity: string) => {
    switch(severity) {
      case 'CRITICAL': return <Badge variant='error'>CRITICAL</Badge>;
      case 'WARNING': return <Badge variant="warning">WARNING</Badge>;
      case 'INFO': return <Badge variant="default">INFO</Badge>;
      default: return <Badge variant="default">{severity}</Badge>;
    }
  };

  const filteredAlerts = alerts?.filter(a => 
    a.title.toLowerCase().includes(searchTerm.toLowerCase()) || 
    a.message.toLowerCase().includes(searchTerm.toLowerCase())
  ) || [];

  return (
    <div className="flex flex-col h-full gap-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold mb-2">System Alerts</h2>
          <p className="text-[var(--text-secondary)] text-sm max-w-2xl">
            Real-time notifications and alerts generated by the monitoring engine.
          </p>
        </div>
      </div>

      {/* Toolbar */}
      <div className="flex items-center gap-4 bg-[var(--bg-card)] p-4 rounded-2xl border border-[var(--border-color)]">
        <div className="flex items-center gap-2 flex-1 max-w-md bg-[rgba(255,255,255,0.03)] border border-[var(--border-color)] rounded-xl px-3 py-2 focus-within:border-[var(--primary)] transition-colors">
          <Search size={16} className="text-[var(--text-secondary)]" />
          <input 
            type="text" 
            placeholder="Search alerts..." 
            className="bg-transparent border-none outline-none text-sm w-full text-[var(--text-primary)] placeholder-[var(--muted)]"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
          />
        </div>
      </div>

      {/* Table */}
      <div className="flex-1 bg-[var(--bg-card)] border border-[var(--border-color)] rounded-2xl overflow-hidden flex flex-col">
        <div className="grid grid-cols-12 gap-4 p-4 border-b border-[var(--border-color)] bg-[rgba(255,255,255,0.02)] text-xs font-semibold text-[var(--muted)] uppercase tracking-wider">
          <div className="col-span-3">Alert</div>
          <div className="col-span-5">Message</div>
          <div className="col-span-2">Severity</div>
          <div className="col-span-2">Time</div>
        </div>
        
        <div className="flex-1 overflow-y-auto">
          {isLoading && (
            <div className="p-8 text-center text-[var(--text-secondary)] animate-pulse">
              Loading alerts...
            </div>
          )}
          
          {error && (
            <div className="p-8 text-center text-[var(--error)]">
              Failed to load alerts history.
            </div>
          )}

          {!isLoading && filteredAlerts.length === 0 && (
             <div className="flex flex-col items-center justify-center p-16 text-center">
               <Bell size={48} className="text-[var(--muted)] mb-4 opacity-50" />
               <h3 className="text-lg font-medium text-[var(--text-primary)] mb-1">No alerts found</h3>
               <p className="text-sm text-[var(--text-secondary)]">Everything is operating normally.</p>
             </div>
          )}

          {!isLoading && filteredAlerts.map((alert) => (
            <div key={alert.id} className="grid grid-cols-12 gap-4 p-4 border-b border-[var(--border-color)] hover:bg-[rgba(255,255,255,0.02)] transition-colors items-center text-sm group">
              <div className="col-span-3 font-medium flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg bg-[rgba(255,255,255,0.05)] flex items-center justify-center border border-[var(--border-color)]">
                  {getSeverityIcon(alert.severity)}
                </div>
                <div className="truncate" title={alert.title}>{alert.title}</div>
              </div>
              <div className="col-span-5 text-[var(--text-secondary)] truncate" title={alert.message}>
                {alert.message}
              </div>
              <div className="col-span-2">
                {getSeverityBadge(alert.severity)}
              </div>
              <div className="col-span-2 text-[var(--text-secondary)] flex items-center gap-2 text-xs">
                <Clock size={12} className="opacity-50" />
                {new Date(alert.created_at).toLocaleString()}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
