"""Alembic migration script template."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c3845eb8a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('expected_status', sa.Integer(), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('check_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('failure_threshold', sa.Integer(), nullable=False),
    sa.Column('latency_threshold_ms', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('health_state', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoints_health_state'), 'endpoints', ['health_state'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False, comment='RFC 5321 max email length'),
    sa.Column('hashed_password', sa.String(length=72), nullable=False, comment='bcrypt hash — never store plaintext'),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False, comment='VIEWER | OPERATOR | ADMIN'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-disable without deleting audit history'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('health_checks',
    sa.Column('endpoint_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_checks_checked_at'), 'health_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_health_checks_endpoint_id'), 'health_checks', ['endpoint_id'], unique=False)
    op.create_table('incidents',
    sa.Column('endpoint_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('failure_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recovery_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('recovery_attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_endpoint_id'), 'incidents', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('alert_events',
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('notification_channel', sa.String(length=50), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_dedup_key'), 'alert_events', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_alert_events_incident_id'), 'alert_events', ['incident_id'], unique=False)
    op.create_index(op.f('ix_alert_events_rule_name'), 'alert_events', ['rule_name'], unique=False)
    op.create_table('recovery_actions',
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_actions_incident_id'), 'recovery_actions', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_actions_incident_id'), table_name='recovery_actions')
    op.drop_table('recovery_actions')
    op.drop_index(op.f('ix_alert_events_rule_name'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_incident_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_dedup_key'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_endpoint_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_health_checks_endpoint_id'), table_name='health_checks')
    op.drop_index(op.f('ix_health_checks_checked_at'), table_name='health_checks')
    op.drop_table('health_checks')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_endpoints_health_state'), table_name='endpoints')
    op.drop_table('endpoints')
    # ### end Alembic commands ###
